package behaviour;

public enum OutputType {
	POS_COVERED, READLENGTH_DIST, READLENGTH_STATISTICS, READS, FILTER, ALIGNMENTS, PERCENTIDENTITY, 
	COVERAGE, EDITDISTANCE, ADDIDTIONALENTRIES, ALIGNMENTDISTRIBUTION, COVERAGEHISTOGRAM, DAMAGE;
}
